defaults:
  - _default_optimizer_settings
  - _self_

name: botorch_qnparego_5

optimizer_import:
  import_from: BenchmarkToolsOptimizers.optimizers.bayesian_optimization.botorch
  import_name: QNParEgo

optimizer_parameters:
  initial_samples: 20
  batch_size: 5


plotting:
  display_name: $QNPAREGO_{5}$
  color: "#377eb8"
  linestyle: dashdot